# Generated by Django 5.2.4 on 2025-07-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_course"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "paid_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Введите дату создания продукта", verbose_name="Дата создания"
                    ),
                ),
                (
                    "paid_status",
                    models.CharField(
                        choices=[("lesson", "Урок оплачен"), ("course", "Курс оплачен")],
                        max_length=10,
                        verbose_name="Статус оплаты",
                    ),
                ),
                ("sum_of_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "Наличный расчет"), ("cashless", "Безналичный расчет")],
                        max_length=10,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="materials.course"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="materials.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите Пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
