# Generated by Django 5.2.4 on 2025-08-16 18:17

import django.utils.timezone
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_payment_paid_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, help_text="Введите ссылку для оплаты", null=True, verbose_name="Ссылка для оплаты"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="price_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID стоимости продукта",
                max_length=100,
                null=True,
                verbose_name="ID стоимости продукта",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(
                blank=True, help_text="Укажите ID продукта", max_length=100, null=True, verbose_name="ID продукта"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите ID сессии", max_length=200, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("canceled", "Отменен"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Укажите дату создания продукта",
                verbose_name="Дата создания",
            ),
        ),
    ]
