# Generated by Django 5.2.4 on 2025-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_payment_link_payment_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите ID сессии", max_length=500, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
