# Generated by Django 5.2.4 on 2025-07-24 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_payments_payment_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Введите дату создания продукта",
                verbose_name="Дата создания",
            ),
        ),
    ]
