# Generated by Django 5.2.4 on 2025-08-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку для оплаты",
                max_length=500,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
    ]
