# Generated by Django 5.2.4 on 2025-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
